image: atnartur/docker:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -f Dockerfile .
  tags:
    - django_backend

test:
  stage: test
  script:
    - docker-compose -f docker-compose.test.yml -p django_backend_tests run app
  after_script:
    - docker-compose -f docker-compose.test.yml -p django_backend_tests down -v
  tags:
    - django_backend

deploy_linux:
  stage: deploy
  script:
    - docker build --file Dockerfile .
  tags:
    - django_backend
  only:
    - master
